//HistoryOrders
export const ORDERS_LOAD_START = 'ORDERS_LOAD_START';
export const ORDERS_LOAD_SUCCESS = 'ORDERS_LOAD_SUCCESS';
export const ORDERS_LOAD_FAIL = 'ORDERS_LOAD_FAIL';

//HistoryForm
export const FILTER_DRIVER_CHANGE = 'FILTER_DRIVER_CHANGE';
export const FILTER_STARTDATE_CHANGE ='FILTER_STARTDATE_CHANGE';
export const FILTER_ENDDATE_CHANGE ='FILTER_ENDDATE_CHANGE';
export const FILTER_STATUS_CHANGE ='FILTER_STATUS_CHANGE';

export const SORT_DIRECTION_CHANGE = 'SORT_DIRECTION_CHANGE';
export const SORT_FIELD_CHANGE = 'SORT_FIELD_CHANGE';