//HistoryOrders
export const ORDERS_LOAD_START = 'ORDERS_LOAD_START';
export const ORDERS_LOAD_SUCCESS = 'ORDERS_LOAD_SUCCESS';
export const ORDERS_LOAD_FAIL = 'ORDERS_LOAD_FAIL';
export const ORDER_ADD = 'ORDER_ADD';
export const ORDER_CHANGE = 'ORDER_CHANGE';
export const ORDER_REMOVE = 'ORDER_REMOVE';

//HistoryForm
export const FILTER_DRIVER_CHANGE = 'FILTER_DRIVER_CHANGE';
export const FILTER_STARTDATE_CHANGE ='FILTER_STARTDATE_CHANGE';
export const FILTER_ENDDATE_CHANGE ='FILTER_ENDDATE_CHANGE';
export const FILTER_STATUS_CHANGE ='FILTER_STATUS_CHANGE';

export const SORT_DIRECTION_CHANGE = 'SORT_DIRECTION_CHANGE';
export const SORT_FIELD_CHANGE = 'SORT_FIELD_CHANGE';

//DriverForm
export const DRIVERS_FILTER_NAME_CHANGE = 'DRIVERS_FILTER_NAME_CHANGE';
export const DRIVERS_SORTDIR_CHANGE = 'DRIVERS_SORTDIR_CHANGE';

//DriversList
export const DRIVER_LOAD_START = 'DRIVER_LOAD_START';
export const DRIVER_LOAD_SUCCESS = 'DRIVER_LOAD_SUCCESS';
export const DRIVER_LOAD_FAILED = 'DRIVER_LOAD_FAILED';
export const DRIVER_CHANGE = 'DRIVER_CHANGE';
export const DRIVER_ADD = 'DRIVER_ADD';
export const DRIVER_REMOVE = 'DRIVER_REMOVE';
